# Information about authentication:
# http://praw.readthedocs.io/en/latest/getting_started/authentication.html#oauth
client_id: "enter your client ID here"
client_secret: "enter your client secret here"
user_agent: "enter your user agent here"
username: "enter your username here"
pw: "enter your password here"

default_file_location: "comments.json"